<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Winners', 'doctrine');

/**
 * BaseWinners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $award_id
 * @property string $fbuser_id
 * @property timestamp $winning_date
 * @property Awards $Awards
 * @property Fbusers $Fbusers
 * 
 * @method integer   getAwardId()      Returns the current record's "award_id" value
 * @method string    getFbuserId()     Returns the current record's "fbuser_id" value
 * @method timestamp getWinningDate()  Returns the current record's "winning_date" value
 * @method Awards    getAwards()       Returns the current record's "Awards" value
 * @method Fbusers   getFbusers()      Returns the current record's "Fbusers" value
 * @method Winners   setAwardId()      Sets the current record's "award_id" value
 * @method Winners   setFbuserId()     Sets the current record's "fbuser_id" value
 * @method Winners   setWinningDate()  Sets the current record's "winning_date" value
 * @method Winners   setAwards()       Sets the current record's "Awards" value
 * @method Winners   setFbusers()      Sets the current record's "Fbusers" value
 * 
 * @package    nokia_facebook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWinners extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nf_winners');
        $this->hasColumn('award_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fbuser_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('winning_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Awards', array(
             'local' => 'award_id',
             'foreign' => 'id'));

        $this->hasOne('Fbusers', array(
             'local' => 'fbuser_id',
             'foreign' => 'fbuser_id'));
    }
}