<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Awards', 'doctrine');

/**
 * BaseAwards
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $winning_moment
 * @property integer $is_available
 * @property Doctrine_Collection $Winners
 * @property Doctrine_Collection $WinnersInformation
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method timestamp           getWinningMoment()      Returns the current record's "winning_moment" value
 * @method integer             getIsAvailable()        Returns the current record's "is_available" value
 * @method Doctrine_Collection getWinners()            Returns the current record's "Winners" collection
 * @method Doctrine_Collection getWinnersInformation() Returns the current record's "WinnersInformation" collection
 * @method Awards              setId()                 Sets the current record's "id" value
 * @method Awards              setWinningMoment()      Sets the current record's "winning_moment" value
 * @method Awards              setIsAvailable()        Sets the current record's "is_available" value
 * @method Awards              setWinners()            Sets the current record's "Winners" collection
 * @method Awards              setWinnersInformation() Sets the current record's "WinnersInformation" collection
 * 
 * @package    nokia_facebook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAwards extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nf_awards');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('winning_moment', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_available', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Winners', array(
             'local' => 'id',
             'foreign' => 'award_id'));

        $this->hasMany('WinnersInformation', array(
             'local' => 'id',
             'foreign' => 'award_id'));
    }
}