<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrackingValidation', 'doctrine');

/**
 * BaseTrackingValidation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property timestamp $created_date
 * 
 * @method integer            getId()           Returns the current record's "id" value
 * @method string             getCode()         Returns the current record's "code" value
 * @method timestamp          getCreatedDate()  Returns the current record's "created_date" value
 * @method TrackingValidation setId()           Sets the current record's "id" value
 * @method TrackingValidation setCode()         Sets the current record's "code" value
 * @method TrackingValidation setCreatedDate()  Sets the current record's "created_date" value
 * 
 * @package    nokia_facebook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrackingValidation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nf_tracking_validation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}