<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Codes', 'doctrine');

/**
 * BaseCodes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $fbuser_id
 * @property string $string_code
 * @property string $user_folder
 * @property timestamp $created_date
 * @property timestamp $played_date
 * @property integer $number_of_second
 * @property integer $finished
 * @property timestamp $finished_date
 * @property Fbusers $Fbusers
 * 
 * @method string    getFbuserId()         Returns the current record's "fbuser_id" value
 * @method string    getStringCode()       Returns the current record's "string_code" value
 * @method string    getUserFolder()       Returns the current record's "user_folder" value
 * @method timestamp getCreatedDate()      Returns the current record's "created_date" value
 * @method timestamp getPlayedDate()       Returns the current record's "played_date" value
 * @method integer   getNumberOfSecond()   Returns the current record's "number_of_second" value
 * @method integer   getFinished()         Returns the current record's "finished" value
 * @method timestamp getFinishedDate()     Returns the current record's "finished_date" value
 * @method Fbusers   getFbusers()          Returns the current record's "Fbusers" value
 * @method Codes     setFbuserId()         Sets the current record's "fbuser_id" value
 * @method Codes     setStringCode()       Sets the current record's "string_code" value
 * @method Codes     setUserFolder()       Sets the current record's "user_folder" value
 * @method Codes     setCreatedDate()      Sets the current record's "created_date" value
 * @method Codes     setPlayedDate()       Sets the current record's "played_date" value
 * @method Codes     setNumberOfSecond()   Sets the current record's "number_of_second" value
 * @method Codes     setFinished()         Sets the current record's "finished" value
 * @method Codes     setFinishedDate()     Sets the current record's "finished_date" value
 * @method Codes     setFbusers()          Sets the current record's "Fbusers" value
 * 
 * @package    nokia_facebook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCodes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nf_codes');
        $this->hasColumn('fbuser_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('string_code', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('user_folder', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('played_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('number_of_second', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('finished', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('finished_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Fbusers', array(
             'local' => 'fbuser_id',
             'foreign' => 'fbuser_id'));
    }
}