<?php

/**
 * Awards
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nokia_facebook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Awards extends BaseAwards
{
}
