<?php

/**
 * AwardsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AwardsTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object AwardsTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Awards');
  }

  public static function getAvailableAwards($submitDate)
  {
/*    $q = Doctrine_Query::create()->select('w.award_id')
      ->from('Winners w');
    $presentAwards = $q->fetchArray();

    if ( ! $presentAwards )
      return NULL;
*/
    $q = Doctrine_Query::create()->select('a.id')
      ->from('Awards a')
      ->where('a.winning_moment <= ?', $submitDate)
      ->andWhere('a.is_available = ?', 1)
//      ->andWhereNotIn('a.id', $presentAwards)
      ->orderBy('a.winning_moment ASC')
      ->limit(1)
      ;

    return $q->fetchOne();
  }
  
  /**
   * Get number of available awards
   * 
   * @author thang.pham
   * @return integer
   */
  public static function numberOfAvailableAwards()
  {
    $q = self::getInstance()->createQuery('a')
      ->select('COUNT(a.id) AS number_of_available_awards')
      ->where('a.is_available = ?', 1);
      
    $result = $q->fetchOne();
    if ($result)
    {
      return $result->getNumberOfAvailableAwards();
    }
    
    return 0;
  }
}