<?php

/**
 * InvitationsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvitationsTable extends Doctrine_Table
{
  const ACCEPTED_METHOD_SINGLE = 'single';
  const ACCEPTED_METHOD_MULTI = 'multi';
  /**
   * Returns an instance of this class.
   *
   * @return object InvitationsTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Invitations');
  }


  public static function updateByInviteeIdAndRequestIds( $inviteeId = 0 , $requestIds = '' )
  {
    $method = InvitationsTable::ACCEPTED_METHOD_SINGLE;

    if ( count( $requestIds ) > 1 )
      $method = InvitationsTable::ACCEPTED_METHOD_MULTI;

    $q = Doctrine_Query::create()->update('Invitations i')
      ->set('i.accepted_method', '?', $method)
      ->set('i.accepted_date', '?', /*new Doctrine_Expression('NOW()')*/date('Y-m-d H:i:s'))
      ->where('i.invitee_id = ?', $inviteeId)
      ->andWhereIn('i.fbrequest_id', $requestIds)
      ->andWhere('i.accepted_date IS NULL');

    return $q->execute();
  }

  public static function updateByInviteeIdAndInviterId( $inviteeId = 0 , $inviterId = 0 )
  {
    $method = InvitationsTable::ACCEPTED_METHOD_SINGLE;

    if ( ! $inviteeId || ! $inviterId )
      return NULL;

    $q = Doctrine_Query::create()->update('Invitations i')
      ->set('i.accepted_method', '?', $method)
      ->set('i.accepted_date', '?', /*new Doctrine_Expression('NOW()')*/date('Y-m-d H:i:s'))
      ->where('i.invitee_id = ?', $inviteeId)
      ->andWhereIn('i.inviter_id', $inviterId)
      ->andWhere('i.accepted_date IS NULL');
    return $q->execute();
  }

  public static function getInviter( $inviteeId = 0 )
  {
    $q = Doctrine_Query::create()
      ->select('i.inviter_id, min(i.accepted_date)')
      ->from('Invitations i')
      ->where('i.invitee_id = ?', $inviteeId)
      ->groupBy('i.invitee_id')
      ->limit(1);

    return $q->fetchOne();
  }
}