<?php

/**
 * TrackingValidationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrackingValidationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrackingValidationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrackingValidation');
    }
}