<?php

/**
 * WinnersTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WinnersTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object WinnersTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Winners');
  }

  /**
   * check already win
   *
   * @param string $fbuserId
   * @return mixed
   */
  public static function checkAlreadyWin($fbuserId)
  {
    $q = Doctrine_Query::create()->select()
      ->from('Winners w')
      ->where('w.fbuser_id = ?', $fbuserId)
      ->limit(1);

    $result = $q->fetchArray();

    return $result ? TRUE : FALSE;
  }
}