<?php

/**
 * WinnersInformationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WinnersInformationTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object WinnersInformationTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('WinnersInformation');
  }

  /**
   * check already submited contact form
   *
   * @param string $fbuserId
   * @return mixed
   */
  public static function checkAlreadySubmitedContact($fbuserId)
  {
    $q = Doctrine_Query::create()->select()
      ->from('WinnersInformation wi')
      ->where('wi.fbuser_id = ?', $fbuserId)
      ->limit(1);

    $result = $q->fetchArray();

    return $result ? TRUE : FALSE;
  }
}