Fbusers:
  connection: doctrine
  tableName: nf_fbusers
  columns:
    user_id:
      type: bigint(20)
      autoincrement: true
    fbuser_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fbuser_email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_first_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_last_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_data:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    modified_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  #relations:
  #  Codes:
  #    local: fbuser_id
  #    foreign: fbuser_id
  #    type: many
Image:
  connection: doctrine
  tableName: nf_image
  columns:
    image_id:
      type: bigint(20)
      notnull: true
      primary: true
      autoincrement: true
    image_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    image_location:
      type: bigint(20)
      primary: true
      notnull: true
    image_description:
      type: string(255)
      notnull: true
    image_like:
      type: bigint(20)
    image_comment:
      type: bigint(20)
    image_uploaded:
      type: timestamp(25)
    image_fbuser_id:
      type: bigint(20)
      notnull: true
  relations:
    Fbusers:
      class: Fbusers
      local: image_fbuser_id
      foreign: user_id
      foreignAlias: Image_Fbuser
      onDelete: CASCADE
    Location:
      class: Location
      local: image_location
      foreign: location_id
  indexes:
    image_id_image_fbuser_id:
      fields: [image_id, image_fbuser_id]
Location:
  connection: doctrine
  tableName: nf_location
  columns:
    location_id:
      type: bigint(20)
      notnull: true
      primary: true
      autoincrement: true
    location_name:
      type: string(255)        
      notnull: false
Comment:
  connection: doctrine
  tableName: nf_comment
  columns:
    comment_id:
      type: bigint(20)
      notnull: true
      primary: true
      autoincrement: true
    comment_status:
      type: boolean
      notnull: true
      default: 1
    comment_date:
      type: timestamp(25)
      notnull: false
    comment_image:
      type: bigint(20)
      notnull: true
    comment_fbuser:
      type: bigint(20)
      notnull: true
  relations:
    Fbusers:
      class: Fbusers
      local: comment_fbuser
      foreign: user_id
      foreignAlias: Comment_Fbuser
      onDelete: CASCADE
    Image:
      class: Image
      local: comment_image
      foreign: image_id
      foreignAlias: Comment_Image
      onDelete: CASCADE
      