Awards:
  connection: doctrine
  tableName: nf_awards
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    winning_moment:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    is_available:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Winners:
      local: id
      foreign: award_id
      type: many
    WinnersInformation:
      local: id
      foreign: award_id
      type: many
Codes:
  connection: doctrine
  tableName: nf_codes
  columns:
    fbuser_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    string_code:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_folder:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    created_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    played_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    number_of_second:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    finished:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    finished_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Fbusers:
      local: fbuser_id
      foreign: fbuser_id
      type: one
Fbusers:
  connection: doctrine
  tableName: nf_fbusers
  columns:
    fbuser_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fbuser_email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_first_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_last_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fbuser_data:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    modified_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Codes:
      local: fbuser_id
      foreign: fbuser_id
      type: many
    Invitations:
      local: fbuser_id
      foreign: invitee_id
      type: many
    Invitations_2:
      class: Invitations
      local: fbuser_id
      foreign: inviter_id
      type: many
    Winners:
      local: fbuser_id
      foreign: fbuser_id
      type: many
    WinnersInformation:
      local: fbuser_id
      foreign: fbuser_id
      type: many
Invitations:
  connection: doctrine
  tableName: nf_invitations
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    fbrequest_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inviter_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    invitee_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    requested_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    accepted_method:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    accepted_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Fbusers:
      local: invitee_id
      foreign: fbuser_id
      type: one
    Fbusers_2:
      class: Fbusers
      local: inviter_id
      foreign: fbuser_id
      type: one
TrackingValidation:
  connection: doctrine
  tableName: nf_tracking_validation
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    code:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Winners:
  connection: doctrine
  tableName: nf_winners
  columns:
    award_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    fbuser_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    winning_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Awards:
      local: award_id
      foreign: id
      type: one
    Fbusers:
      local: fbuser_id
      foreign: fbuser_id
      type: one
WinnersInformation:
  connection: doctrine
  tableName: nf_winners_information
  columns:
    fbuser_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    award_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    first_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    last_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email_address:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mailing_address:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    zip_code:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    created_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    modified_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Awards:
      local: award_id
      foreign: id
      type: one
    Fbusers:
      local: fbuser_id
      foreign: fbuser_id
      type: one
